In [71]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing

In [142]:
# Season: 1 = Summer, 0 = Winter
# Time: 1 = Day, 0 = Night
# Output: 1 = Converges, 0 = Explodes

df = pd.read_csv(r'C:\Users\Rohan\Desktop\Big Data\PSSE Files\Data\Data.csv')
df

Bus  Voltage  Season  Time  Demand  Renewables  Output
0       1   1.0796       1     1     100           8       1
1       2   1.0988       1     1     100           8       1
2       3   1.0841       1     1     100           8       1
3       4   1.0650       1     1     100           8       1
4       5   1.0643       1     1     100           8       1
...   ...      ...     ...   ...     ...         ...     ...
2725   35   1.0469       0     0     200          50       0
2726   36   1.0829       0     0     200          50       0
2727   37   1.0804       0     0     200          50       0
2728   38   1.0920       0     0     200          50       0
2729   39   1.0313       0     0     200          50       0

[2730 rows x 7 columns]

## Linear Regression

In [143]:
X = df[['Season', 'Time', 'Demand', 'Renewables']]
y = df[['Voltage','Output']]

In [144]:
regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [145]:
predicted = regr.predict([[1, 0, 120, 8]])

In [146]:
print(predicted)

[[0.96253003 0.7546362 ]]


In [147]:
print(regr.intercept_)
print(regr.coef_)

[1.57362168 2.24217126]
[[-0.00835802  0.01984549 -0.00486664 -0.00234212]
 [-0.02644878  0.05714286 -0.01175314 -0.00633863]]


In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [164]:
# Instantiate model
lm2 = linear_model.LinearRegression()

# Fit Model
lm2.fit(X_train, y_train)

# Predict
y_pred = lm2.predict(X_test)
y_pred

array([[ 0.97808678,  0.7537333 ],
       [ 0.82040276,  0.41164477],
       [ 0.80301853,  0.37757853],
       [ 0.50891825, -0.36567386],
       [ 0.93374818,  0.67954483],
       [ 0.58256448, -0.14630438],
       [ 0.50501447, -0.39161103],
       [ 1.02654123,  0.88716219],
       [ 0.79911475,  0.35164136],
       [ 0.99903007,  0.81747972],
       [ 0.74675653,  0.1922753 ],
       [ 0.99512629,  0.79154255],
       [ 0.73634472,  0.16984697],
       [ 0.97557492,  0.79759279],
       [ 0.98849859,  0.77616163],
       [ 1.01334565,  0.86584523],
       [ 0.94031605,  0.68548087],
       [ 0.50501447, -0.39161103],
       [ 0.90233325,  0.58392519],
       [ 0.73244095,  0.14390979],
       [ 0.74675653,  0.1922753 ],
       [ 0.89180176,  0.5426071 ],
       [ 1.00944187,  0.83990805],
       [ 1.00944187,  0.83990805],
       [ 0.82430654,  0.43758195],
       [ 0.97418301,  0.72779613],
       [ 0.87748618,  0.49424159],
       [ 1.02654123,  0.88716219],
       [ 0.78870295,

In [165]:
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

0.29907966110531076


In [166]:
score = lm2.score(X_test, y_test)
print(score)

0.4371070028355259


## kNN Trials

In [167]:
# KNN Trials

lab_enc = preprocessing.LabelEncoder()
y_train_encoded = lab_enc.fit_transform(y_train)

knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test)
ypred

ValueError: y should be a 1d array, got an array of shape (2457, 2) instead.

In [ ]:
result = confusion_matrix(y_test, ypred)
print(result)
result1 = classification_report(y_test, ypred)
print (result1)
result2 = accuracy_score(y_test,ypred)
print(result2)

# Decision Tree

In [168]:
from sklearn.tree import DecisionTreeRegressor
clf = DecisionTreeRegressor(random_state=0)

In [169]:
#Training the decision tree classifier. 
clf.fit(X_train, y_train)

y_pred =  clf.predict(X_test)
X_test

Season  Time  Demand  Renewables
1090       0     0     100          50
1921       1     0     150           8
2298       0     1     150          25
2659       0     1     200          50
1683       0     0     120          25
...      ...   ...     ...         ...
2040       1     1     150          25
1511       0     1     120           8
806        0     1     100          20
2016       1     0     150          15
1015       0     1     100          50

[273 rows x 4 columns]

In [170]:
y_pred

array([[1.04828824, 1.        ],
       [0.66145937, 0.        ],
       [0.64267647, 0.        ],
       [0.67264194, 0.        ],
       [1.00622727, 1.        ],
       [0.65592353, 0.        ],
       [0.65682   , 0.        ],
       [1.06903438, 1.        ],
       [0.63883437, 0.        ],
       [1.05890588, 1.        ],
       [0.68324706, 0.        ],
       [1.06113235, 1.        ],
       [0.70145405, 0.        ],
       [1.04841613, 1.        ],
       [1.06923243, 1.        ],
       [1.06812647, 1.        ],
       [1.02852571, 1.        ],
       [0.65682   , 0.        ],
       [0.68518182, 0.        ],
       [0.69494444, 0.        ],
       [0.68324706, 0.        ],
       [0.70455429, 0.        ],
       [1.06995588, 1.        ],
       [1.06995588, 1.        ],
       [0.66684   , 0.        ],
       [1.05675294, 1.        ],
       [0.71649355, 0.        ],
       [1.06903438, 1.        ],
       [0.64198857, 0.        ],
       [1.01876061, 1.        ],
       [1.

In [171]:
score = clf.score(X_train, y_train)
print("R-squared:", score) 

R-squared: 0.7007456790949369


In [172]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
print("RMSE: ", mse*(1/2.0)) 

MSE:  0.035862008120904065
RMSE:  0.017931004060452033


In [173]:
predict_1 = clf.predict([[1, 1, 100, 5]])

In [174]:
print(predict_1)

[[1.07437632 1.        ]]


In [175]:
adj_r = 1 - (1-clf.score(X_train, y_train))*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)

In [176]:
print(adj_r)

0.7002574991260868
