In [198]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing

In [199]:
# Season: 1 = Summer, 0 = Winter
# Time: 1 = Day, 0 = Night
# Output: 1 = Converges, -1 = Explodes

df = pandas.read_csv(r'C:\Users\Rohan\Desktop\Big Data\PSSE Files\Data\Data.csv')
df

Bus  Voltage  Season  Time  Demand  Renewables  Output
0       1   1.0796       1     1     100           8       1
1       2   1.0988       1     1     100           8       1
2       3   1.0841       1     1     100           8       1
3       4   1.0650       1     1     100           8       1
4       5   1.0643       1     1     100           8       1
...   ...      ...     ...   ...     ...         ...     ...
2725   35   1.0469       0     0     200          50      -1
2726   36   1.0829       0     0     200          50      -1
2727   37   1.0804       0     0     200          50      -1
2728   38   1.0920       0     0     200          50      -1
2729   39   1.0313       0     0     200          50      -1

[2730 rows x 7 columns]

## Linear Regression

In [221]:
X = df[['Season', 'Time', 'Demand', 'Renewables']]
y = df[['Voltage','Output']]

In [222]:
regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [223]:
predicted = regr.predict([[1, 0, 120, 8]])

In [224]:
print(predicted)

[[0.96253003 0.50927239]]


In [225]:
print(regr.intercept_)
print(regr.coef_)

[1.57362168 3.48434251]
[[-0.00835802  0.01984549 -0.00486664 -0.00234212]
 [-0.05289755  0.11428571 -0.02350629 -0.01267725]]


In [226]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [227]:
# Instantiate model
lm2 = linear_model.LinearRegression()

# Fit Model
lm2.fit(X_train, y_train)

# Predict
y_pred = lm2.predict(X_test)
y_pred

array([[ 0.91328541,  0.22811004],
       [ 0.79258878, -0.34991244],
       [ 0.52825065, -1.71737651],
       ...,
       [ 0.60282778, -1.3224675 ],
       [ 0.50508632, -1.81925824],
       [ 0.96459076,  0.50473553]])

In [228]:
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

0.4370572702866801


## kNN Trials

In [219]:
# KNN Trials

lab_enc = preprocessing.LabelEncoder()
y_train_encoded = lab_enc.fit_transform(y_train)

knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test)
ypred

C:\Users\Rohan\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Rohan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([ 1, -1, -1, -1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1,
       -1, -1,  1,  1, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1, -1,  1,  1,
        1, -1, -1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1,  1,
        1, -1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1,
        1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
       -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1, -1,
       -1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1,  1,
       -1,  1, -1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1, -1,
        1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,
        1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1, -1, -1,  1,
        1, -1, -1,  1,  1, -1,  1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1,
       -1, -1, -1, -1, -1

In [220]:
result = confusion_matrix(y_test, ypred)
print(result)
result1 = classification_report(y_test, ypred)
print (result1)
result2 = accuracy_score(y_test,ypred)
print(result2)

[[278   0]
 [  0 405]]
              precision    recall  f1-score   support

          -1       1.00      1.00      1.00       278
           1       1.00      1.00      1.00       405

    accuracy                           1.00       683
   macro avg       1.00      1.00      1.00       683
weighted avg       1.00      1.00      1.00       683

1.0
